<a href="https://colab.research.google.com/github/Redcoder815/Deep_learning_phitron/blob/main/08Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
if torch.cuda.is_available():
  print('Gpu is available')
  print(f'Device name {torch.cuda.get_device_name(0)}')
else:
  print('Gpu is not available')

Gpu is not available


In [3]:
a = torch.empty(2,3)
a

tensor([[8.9012e-25, 4.3292e-41, 8.9012e-25],
        [4.3292e-41, 1.6333e-38, 0.0000e+00]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.9046, 0.0036, 0.3125],
        [0.0588, 0.4567, 0.0057]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [12]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[          443360176,           438776256,   72340172838076673],
        [7308604897285731073,                  48,                  48]])

In [15]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [16]:
x.dtype

torch.int64

In [17]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [18]:
x.to(dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [20]:
x // 3

tensor([[0, 0, 1],
        [1, 1, 2]])

In [21]:
x%2

tensor([[1, 0, 1],
        [0, 1, 0]])

In [22]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [23]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [24]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [26]:
c = torch.tensor([-1, -2, -3, -4])

torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
d = torch.tensor([1, 2, 3, 4])

torch.neg(d)

tensor([-1, -2, -3, -4])

In [28]:
d = torch.tensor([100, 200, 300, 400])

torch.clamp(d, min = 1, max = 2)

tensor([2, 2, 2, 2])

In [29]:
e = torch.randint(size = (2, 3), low = 0, high = 10, dtype = torch.float32)

In [30]:
torch.sum(e)

tensor(27.)

In [31]:
torch.mean(e)

tensor(4.5000)

In [32]:
torch.sum(e, dim = 0)

tensor([9., 9., 9.])

In [33]:
torch.sum(e, dim = 1)

tensor([10., 17.])

In [34]:
torch.prod(e)

tensor(0.)

In [35]:
f = torch.randint(size = (2, 3), low = 0, high = 10)
g = torch.randint(size = (3, 2), low = 0, high = 10)

In [36]:
torch.matmul(f, g)

tensor([[ 21,  63],
        [ 82, 130]])

In [37]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [38]:
torch.dot(vector1, vector2)

tensor(11)

In [39]:
f

tensor([[7, 0, 0],
        [9, 5, 7]])

In [40]:
torch.transpose(f, 0, 1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [41]:
h = torch.randint(size = (3, 3), low = 0, high = 10, dtype = torch.float32)

In [42]:
torch.det(h)

tensor(184.0000)

In [43]:
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

In [44]:
i = torch.randint(size = (2, 3), low = 0, high = 10, dtype = torch.float32)
j = torch.randint(size = (2, 3), low = 0, high = 10, dtype = torch.float32)

In [45]:
i

tensor([[9., 2., 6.],
        [7., 7., 8.]])

In [46]:
j

tensor([[3., 6., 1.],
        [5., 5., 0.]])

In [47]:
i > j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [48]:
i != j

tensor([[True, True, True],
        [True, True, True]])

In [49]:
k = torch.tensor([10, 20, 30])

torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [50]:
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [52]:
torch.relu(k)

tensor([10, 20, 30])

In [53]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [54]:
m.add_(n)

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

In [55]:
a = torch.tensor([1,2,3,4,5])

In [56]:
b = a

In [57]:
b[2] = 30
b

tensor([ 1,  2, 30,  4,  5])

In [58]:
a

tensor([ 1,  2, 30,  4,  5])

In [59]:
b = a.clone()
b

tensor([ 1,  2, 30,  4,  5])

In [60]:
id(a)

132687681370016