<a href="https://colab.research.google.com/github/Redcoder815/Deep_learning_phitron/blob/main/09Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

data = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [4]:
X = data[:,0:2].float()
y = data[:,2].float()

In [5]:
X

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

In [6]:
y

tensor([3., 4., 5.])

In [7]:
def initialize_parameters(layer_dims):
  torch.manual_seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters["W" + str(l)] = torch.ones((layer_dims[l-1], layer_dims[l])) * 0.1
    parameters["b" + str(l)] = torch.zeros((layer_dims[l], 1))

  return parameters

In [8]:
initialize_parameters( [2,2,1] )

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

In [9]:
def linear_forward(A_prev, W, b):
  Z = torch.matmul(W.T, A_prev) + b
  return Z

In [11]:
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2
  print('Length of parameters ', L)
  for l in range(1,L+1):
    A_prev = A

    wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    A = linear_forward( A_prev, wl, bl )

  return A, A_prev

In [12]:
params = initialize_parameters([2,2,1])
X_sample = X[0].reshape(2,1)
y_hat, A1 = L_layer_forward(X_sample,params)

Length of parameters  2


In [13]:
def update_parameters(parameters, y, y_hat, A1, X, lr=0.001):

    err_signal = 2 * (y - y_hat)

     #  Save OLD W2 values before updating
    W2_00_old = parameters['W2'][0, 0].item()
    W2_10_old = parameters['W2'][1, 0].item()

    # Update Layer 2




    parameters['W2'][0, 0] += lr * err_signal * A1[0, 0]
    parameters['W2'][1, 0] += lr * err_signal * A1[1, 0]
    parameters['b2'][0, 0] += lr * err_signal #


    parameters['W1'][0, 0] += lr * err_signal * parameters['W2'][0, 0] * X[0, 0]
    parameters['W1'][0, 1] += lr * err_signal * parameters['W2'][0, 0] * X[1, 0]
    parameters['b1'][0, 0] += lr * err_signal * parameters['W2'][0, 0]

    parameters['W1'][1, 0] += lr * err_signal * parameters['W2'][1, 0] * X[0, 0]
    parameters['W1'][1, 1] += lr * err_signal * parameters['W2'][1, 0] * X[1, 0]
    parameters['b1'][1, 0] += lr * err_signal * parameters['W2'][1, 0]

    return parameters

In [16]:
params = initialize_parameters([2, 2, 1])
epochs = 15

for i in range(epochs):
    epoch_loss = 0
    for j in range(X.shape[0]):
        # Prepare sample
        X_sample = X[j].reshape(2, 1)
        y_sample = y[j]

        print(f'X_sample {X_sample}')
        print(f'y_sample {y_sample}')

        # Forward
        y_hat, A1 = L_layer_forward(X_sample, params)
        y_hat_scalar = y_hat[0, 0]

        # Update
        print(f'Old parames {params}')
        params = update_parameters(params, y_sample, y_hat_scalar, A1, X_sample)
        print(f'iteration i and j {i} and {j} er parames {params}')

        # Loss calculation
        loss = (y_sample - y_hat_scalar) ** 2
        epoch_loss += loss.item()

    print(f"Epoch - {i+1} Loss - {epoch_loss / X.shape[0]}")

X_sample tensor([[2.],
        [3.]])
y_sample 3.0
Length of parameters  2
Old parames {'W1': tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]]), 'b1': tensor([[0.],
        [0.]]), 'W2': tensor([[0.1000],
        [0.1000]]), 'b2': tensor([[0.]])}
iteration i and j 0 and 0 er parames {'W1': tensor([[0.1012, 0.1018],
        [0.1012, 0.1018]]), 'b1': tensor([[0.0006],
        [0.0006]]), 'W2': tensor([[0.1029],
        [0.1029]]), 'b2': tensor([[0.0058]])}
X_sample tensor([[5.],
        [6.]])
y_sample 4.0
Length of parameters  2
Old parames {'W1': tensor([[0.1012, 0.1018],
        [0.1012, 0.1018]]), 'b1': tensor([[0.0006],
        [0.0006]]), 'W2': tensor([[0.1029],
        [0.1029]]), 'b2': tensor([[0.0058]])}
iteration i and j 0 and 1 er parames {'W1': tensor([[0.1054, 0.1068],
        [0.1054, 0.1068]]), 'b1': tensor([[0.0014],
        [0.0014]]), 'W2': tensor([[0.1113],
        [0.1113]]), 'b2': tensor([[0.0133]])}
X_sample tensor([[7.],
        [8.]])
y_sample 5.0
Length of par